on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://dev.to/feed/devemloop'
          file: 'README.md'
          tart_flag: "<!-- blog:start -->"
          end_flag: "<!-- blog:end -->"
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "readme: update posts" || true
          git push
